export const pessoaslista = [
  {
    id: 1,
    name: "Wega",
    idade: 9001,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTDYKsSPLrk8MJyHAsZpSTTa2GQoH3IjXKBkg&s",
    cidade: "Wega's Challenge",
    profissao: "Hambúrguer",
  },
  {
    id: 2,
    name: "Kratos deus da guerra",
    idade: 100,
    image: "https://i.ytimg.com/vi/uITuEjt3Cm4/mqdefault.jpg",
    cidade: "Esparta",
    profissao: "Caçador de deuses gregos",
  },
  {
    id: 3,
    name: "Ted Estanho",
    idade: 31,
    image: "https://t4.ftcdn.net/jpg/05/31/37/89/360_F_531378938_xwRjN9e5ramdPj2coDwHrwk9QHckVa5Y.jpg",
    cidade: "Nova York",
    profissao: "Ser estranho",
  },
  {
    id: 4,
    name: "Soos",
    idade: 22,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgbSFvBMApBvUDRh2TuRww40IlH3T5DCBzPA&s",
    cidade: "Gravity Falls",
    profissao: "Dono de casa pra turistas",
  },
  {
    id: 5,
    name: "Bomberhomem atomico",
    idade: 1993,
    image: "https://static.wikia.nocookie.net/bomberman/images/b/b3/Atomic_Bomberman_Box.jpg/revision/latest?cb=20110928164841",
    cidade: "CED da antiga Hudson Soft",
    profissao: "Ser um jogo",
  },
  {
    id: 6,
    name: "Mamãe Luigi",
    idade: 30,
    image: "https://static.wikia.nocookie.net/mario/images/9/96/Mama_Luigi.png/revision/latest/thumbnail/width/360/height/360?cb=20260307154750",
    cidade: "Reino dos cogumelos",
    profissao: "Encanador",
  },
  {
    id: 7,
    name: "Daft",
    idade: 37,
    image: "https://djmag.com/sites/default/files/styles/djm_23_1005x565/public/2022-11/thomabangalterhelmetmain-1250x500_0.jpg.webp?itok=mu_YRt4G50296922",
    cidade: "França (sim, é uma cidade simsimsim)",
    profissao: "Produtor musical",
  },
  {
    id: 8,
    name: "Punk",
    idade: 37,
    image: "https://i.pinimg.com/474x/d2/2a/5d/d22a5d6efb2fbb2cd6eb98d49c0e96c5.jpg",
    cidade: "França (sim)",
    profissao: "Produtor musical",
  },
  {
    id: 9,
    name: "Família",
    idade: 35,
    image: "https://static.wikia.nocookie.net/universalstudios/images/d/d7/6460161-2352384703-latest.jpg/revision/latest/thumbnail/width/360/height/450?cb=20211024143111",
    cidade: "Família land",
    profissao: "Ser leal a family",
  },
  {
    id: 10,
    name: "preguiça",
    idade: 1000000,
    image: "https://www.correiobraziliense.com.br/aqui/wp-content/uploads/2025/07/bicho_preguica.jpg",
    cidade: "sim",
    profissao: "CHEGAAAAAAAAAAAAAAAAAA",
  }
];
